name: test_app_felix
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_svg: ^2.0.9
  
  auto_route: ^7.8.4

  easy_localization: ^3.0.3

  sprintf: ^7.0.0

  yandex_mapkit: ^3.4.0
  
  geolocator: ^10.1.0

  freezed: ^2.4.7

  freezed_annotation: ^2.4.1
  
  json_serializable: ^6.7.1
  
  json_annotation: ^4.8.1

  dartz: ^0.10.1
  
  data_connection_checker_nulls: ^0.0.2

  get_it: ^7.6.7

  bloc: ^8.1.3
  
  flutter_bloc: ^8.1.4
  
  dio: ^5.4.0
  
  pretty_dio_logger: ^1.3.1
  
  shared_preferences: ^2.2.2
  
  mask_text_input_formatter: ^2.9.0
  



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner: ^2.4.8

  flutter_gen_runner: ^5.2.0
  
  auto_route_generator: ^7.3.2

  locale_gen: ^12.0.0







flutter_gen:
  output: lib/gen/
  lineLength: 120

  integrations:
    flutter_svg: true

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages


  
  assets:
    - assets/
    - assets/fonts/
    - assets/png/
    - assets/svg/
    - assets/locale/

  
  # fonts:
    # - family: Schyler
    #   fonts:
    #     - asset: fonts/Schyler-Regular.ttf
    #     - asset: fonts/Schyler-Italic.ttf
    #       style: italic
    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


locale_gen:
  default_language: 'en'
  languages: ['en','ru','uz','es']
  locale_assets_path: 'assets/locale/'
  assets_path: 'assets/locale/'
  output_path: 'lib/gen/'
  doc_languages: ['en']